<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>DragonPixel.Runtime.Worker</AssemblyName>
    <RootNamespace>DragonPixel.Runtime.Worker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DragonPixel.Contracts\DragonPixel.Contracts.csproj" />
    <ProjectReference Include="..\DragonPixel.NativeInterop\DragonPixel.NativeInterop.csproj" />
  </ItemGroup>
</Project>
