<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>DragonPixel.ProjectComponents</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="*.cs" />
    <Reference Include="DragonPixel.Contracts">
      <HintPath>$(DPEContractsPath)</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
